name = "tuchuang"
main = "src/index.js"
compatibility_date = "2026-04-27"
compatibility_flags = ["nodejs_compat"]

[ai]
binding = "AI"

[observability]
enabled = true
head_sampling_rate = 1

[vars]
AI_MODEL = "@cf/meta/llama-4-scout-17b-16e-instruct"

# 添加下面三行，强制 Wrangler 使用 Node.js 兼容模式打包
[build]
command = ""
[build.upload]
format = "service-worker"
